config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # get 'pages/home'
  root "pages#home"

  # get 'pages/about'
  get 'about', to: 'pages#about'

  # get 'pages/contact'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder

  after_initialize :set_defaults
  scope :ror_portfolio_items, -> {where(subtitle: 'RoR')}
  has_many :technologies
  validates_presence_of :title, :body, :main_image, :thumb_image
  accepts_nested_attributes_for :technologies, reject_if: lambda {|attrs| attrs['name'].blank? }

  def self.angular
  where(subtitle: 'Angular')
  end

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600',width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350',width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
  before_action :set_portfolio_item, only: %i[edit update show destroy]
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(porfolio_params)
    respond_to do |format|
      if @portfolio_item.save!
        format.html { redirect_to portfolios_path, notice: "portfolio_item was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(porfolio_params)
        format.html { redirect_to portfolios_path, notice: "Portfolio was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def destroy
    @portfolio_item.destroy
    # Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: "Portfolio was successfully destroyed." }
    end
  end

  private

  def porfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      technologies_attributes: [:name]
                                      )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: @portfolio_item) do |form| %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<h2><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h2>
<p><%= portfolio_item.subtitle %></p>
<p><%= portfolio_item.body %></p>
<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
<p><%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %></p>
<%= link_to "Delete", portfolio_path(portfolio_item), method: :delete, data: {turbo_method: :delete, confirm: 'Are ypu sure'} if logged_in?(:site_admin)%>
<%= button_to "Destroy this portfolio", portfolio_path(portfolio_item), method: :delete if logged_in?(:site_admin) %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>
<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>
<% @angular_portfolio_items.each do |portfolio_item| %>
  <h2><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h2>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <p><%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %></p>
  <%= link_to "Delete", portfolio_path(portfolio_item), method: :delete, data: {turbo_method: :delete, confirm: 'Are ypu sure'} if logged_in?(:site_admin)%>
  <%= button_to "Destroy this blog", portfolio_path(portfolio_item), method: :delete %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit new Portfolio</h1>

<%= render "form", portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>
<%= link_to "Create New Portfolio Item", new_portfolio_path if logged_in?(:site_admin) %>
<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create new Portfolio</h1>

<%= render "form", portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<h1>Show</h1>
<%= image_tag @portfolio_item.main_image %>
<h1><%= @portfolio_item.title %></h1>
<em><%= @portfolio_item.subtitle %></em>
<p><%= @portfolio_item.body %></p>

<h2>Technologies Used:</h2>
<% @portfolio_item.technologies.each do |t| %>
  <p> <%= t.name %></p>
<% end %>