config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # get 'pages/home'
  root "pages#home"

  # get 'pages/about'
  get 'about', to: 'pages#about'

  # get 'pages/contact'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
end

app/views/shared/_application_footer.html.erb
      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p><%= generate_copyright %></p>
        </div>
      </footer>

app/views/shared/_application_navbar.html.erb
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">Aadil RT</h3>

          <nav class="nav nav-masthead justify-content-center">
            <%= link_to "Home", root_path, class: 'nav-link' %>
            <%= link_to "About", about_path, class: 'nav-link' %>
            <%= link_to "Contact", contact_path, class: 'nav-link' %>
            <%= link_to "Blogs", blogs_path, class: 'nav-link' %>
            <%= link_to "Portfolios", portfolios_path, class: 'nav-link' %>
            <%= login_register_button_toggle_helper('nav-link') %>

          </nav>

        </div>
      </header>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= link_to "Home", root_path, class: 'nav-link'%>
      <%= link_to "About", about_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "Blogs", blogs_path, class: 'nav-link' %>
      <%= link_to "Portfolios", portfolios_path, class: 'nav-link' %>
      <%= login_register_button_toggle_helper('nav-link') %>
    </nav>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class= "<%= location %>"  >
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blogs", blogs_path %></div>
  <div><%= link_to "Portfolios", portfolios_path %></div>
</div>